FROM openjdk:8 as gameoflife-war
LABEL AUTHOR="Kishore"
RUN apt-get update
RUN apt-get install maven -y
RUN apt-get install git -y
RUN git clone https://github.com/wakaleo/game-of-life.git
RUN cd game-of-life && mvn package

FROM tomcat:8
COPY --from=gameoflife-war /game-of-life/gameoflife-web/target/gameoflife*.war /usr/local/tomcat/webapps/gameoflife.war
